### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by baibai25** [baibai25/NLP-YouTube-Live#1]
# Download issues
## Known Issues
Sometimes a Syntax Error occurs.

e.g.
```
$ python get_comment.py 'https://www.youtube.com/watch?v=4jQdiyOqD8U&t=677s'

Traceback (most recent call last):
  File "get_comment.py", line 88, in <module>
    data.get_comment()
  File "get_comment.py", line 51, in get_comment
    dics = eval(dict_str)
  File "<string>", line 1

 {"responseContext":{"serviceTrackingParams":[{....
.....
ion":{"item":{"liveChatTextMessageRenderer":{"message":{"runs":[{"text":"2 / 2

SyntaxError: EOL while scanning string literal
```
A SyntaxError occurs because the downloaded data is incomplete and cannot be converted to a dictionary type.

## Cause
Some URL's can successfully downloaded comment data. I am now investigating the causes. 

Followings are possible causes.
1. Streamer's network connection problem
(Occasionally live streaming will be disconnected due to the network problems.)

2. Super Chat, Super Stickers and Membership

## Notice
My goal is to analyze YouTube Live comments. Therefore, the priority of this issue is very low.

**Comment by baibai25** [comment]
# Cause
The cause was limitations of the array in the data structure. Some videos (archived streams) is stored comments in multiple arrays. Therefore, I fixed the my code. 2eefc97
